apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
          protocol: TCP

    - name: curl-container
      image: curlimages/curl:latest
      command: ["tail"]
      args: ["-f", "/dev/null"]

    - name: nginx-container2
      image: nginx:latest
      ports:
        - containerPort: 80
          protocol: TCP
