apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-pods-label
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      command: ["tail"]
      args: ["-f", "/dev/null"]
