apiVersion: v1
kind: Service
metadata:
  name: www-service
spec:
  type: NodePort
  selector:
    app: www-pod-label
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30001
