apiVersion: v1
kind: PersistentVolume
metadata:
  name: m-pv-2
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.64.20
    path: /nfs_root/volume

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: m-pvc-2-5g
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m-www-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: m-www-pod-label
  template:
    metadata:
      name: m-www-pod
      labels:
        app: m-www-pod-label
    spec:
      volumes:
        - name: www-storage
          persistentVolumeClaim:
            claimName: m-pvc-2-5g
      containers:
        - name: m-www-container
          image: nginx:latest
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: www-storage
