apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/edbergbak/work/k8s/pv_pvc/volume_1"
