apiVersion: v1
kind: Service
metadata:
  name: hn-service
spec:
  type: NodePort
  selector:
    app: hn-pod-label
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30001
