apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-test-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-test-pod-label
  template:
    metadata:
      name: web-test-pod
      labels:
        app: web-test-pod-label
    spec:
      containers:
        - name: web-test-container
          image: web_test_image:1
          ports:
            - containerPort: 80
              protocol: TCP
